import type { TacticCard } from './cards.ts';

export const VOID_CARDS: TacticCard[] = [
  // ── Void Shop Cards (6 new) ────────────────────────────────────────────────
  {
    id: 'echo_drain',
    name: 'Echo Drain',
    description: 'Hull −10. +echo = rnd #.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 0,
    energyRefund: { condition: 'Random 50%', amount: 1 },
  },
  {
    id: 'void_siphon',
    name: 'Void Siphon',
    description: 'Costs 0⚡. Refund 0-1⚡ randomly. +2 echo.',
    rarity: 'rare',
    lootNodeEligible: false,
    energyCost: 0,
    energyRefund: { condition: 'Random 0-1⚡', amount: 1 },
  },
  {
    id: 'void_touched',
    name: 'Void Touched',
    description: '+1 echo on extract. Hull <30: +1 more.',
    rarity: 'rare',
    lootNodeEligible: false,
    energyCost: 2,
  },
  {
    id: 'desperate_measures',
    name: 'Desperate Measures',
    description: 'Hull −20. +10000₡. Shld +2.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'debt_renegotiation',
    name: 'Debt Renegotiation',
    description: 'Debt −20000₡. −5000₡.',
    rarity: 'rare',
    lootNodeEligible: false,
    energyCost: 2,
  },
  {
    id: 'last_gasp',
    name: 'Last Gasp',
    description: 'Hull ≤25: +8000₡ +2 shld. Else: +2000₡.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'scorched_extract',
    name: 'Scorched Extract',
    description: 'End dive. Hull −30. +3 echo.',
    rarity: 'rare',
    lootNodeEligible: false,
    energyCost: 2,
  },

  // ── Death Lesson Cards (4 new) ────────────────────────────────────────────
  {
    id: 'bitter_experience',
    name: 'Bitter Experience',
    description: 'Hull ≤35: +6000₡ skip dng. Else +2000₡.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'scrap_memory',
    name: 'Scrap Memory',
    description: '+4000₡. +2 scrap. Hull <40: +1 echo.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'defiant_last_stand',
    name: 'Defiant Last Stand',
    description: 'Hull ≤20 & shld=0: +3 shld +5000₡.',
    rarity: 'rare',
    lootNodeEligible: false,
    energyCost: 2,
  },
  {
    id: 'survivors_instinct',
    name: "Survivor's Instinct",
    description: 'Debt >500000₡: extract +50%. Else: +3000₡.',
    rarity: 'rare',
    lootNodeEligible: false,
    energyCost: 2,
  },

  // ── Research Track Void Cards (6 cards) ────────────────────────────────────
  {
    id: 'void_pulse',
    name: 'Void Pulse',
    description: 'Spend all shld. +echo=shld+1. Hull −5/shld.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'entropy_gift',
    name: 'Entropy Gift',
    description: '+4000₡. Hull <40: +1 shld.',
    rarity: 'common',
    lootNodeEligible: false,
    energyCost: 0,
  },
  {
    id: 'ancestral_extract',
    name: 'Ancestral Extract',
    description: 'End dive. +2 echo. Preview next run dng.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'premonition',
    name: 'Premonition',
    description: 'Preview 3 dng. Skip next dng.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'echo_amplifier_card',
    name: 'Echo Amplifier',
    description: '+1 echo. Next extract: +1 echo.',
    rarity: 'rare',
    lootNodeEligible: false,
    energyCost: 2,
  },
  {
    id: 'void_communion_card',
    name: 'Void Communion',
    description: 'Hull −15. +2 echo. +2 cards next rnd.',
    rarity: 'rare',
    lootNodeEligible: false,
    energyCost: 2,
  },
];
