import type { TacticCard } from './cards.ts';

export const CORPORATE_CARDS: TacticCard[] = [
  // ── Common (7 cards) ───────────────────────────────────────────────────────
  {
    id: 'salvage_sweep',
    name: 'Salvage Sweep',
    description: '4-8 scrap. +1 card next rnd.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 1,
    overchargeEffect: { multiplier: 1.5, description: '+50% scrap (6-12) and +2 cards next round' },
  },
  {
    id: 'routine_extract',
    name: 'Routine Extract',
    description: 'End dive. +15% extract bonus.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 0,
  },
  {
    id: 'protocol_scan',
    name: 'Protocol Scan',
    description: 'Preview 2 dng. Next dng −10%.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 1,
  },
  {
    id: 'debt_audit',
    name: 'Debt Audit',
    description: 'Debt −3000₡ this run.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 0,
  },
  {
    id: 'risk_assessment',
    name: 'Risk Assessment',
    description: 'Analyze next dng. 2-4 scrap.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 0,
    overchargeEffect: { multiplier: 1.5, description: '+50% scrap (3-6) and deeper analysis (preview 2 dangers)' },
  },
  {
    id: 'hull_investment_prep',
    name: 'Hull Investment Prep',
    description: 'Hull −10. Extract +15%.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 1,
  },
  {
    id: 'efficiency_drive',
    name: 'Efficiency Drive',
    description: '+25% extract bonus.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 1,
  },
  {
    id: 'efficiency_burst',
    name: 'Efficiency Burst',
    description: '0⚡ cost. +1⚡ gained. −5 hull stress.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 0,
    isSurge: true,
  },
  {
    id: 'corporate_incentive',
    name: 'Corporate Incentive',
    description: 'Gain 1⚡. +10% extract bonus.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 0,
    isSurge: true,
  },

  // ── Uncommon (12 cards) ────────────────────────────────────────────────────
  {
    id: 'corporate_override',
    name: 'Corporate Override',
    description: 'Negate next dng. Debt +5000₡.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
    energyRefund: { condition: 'Spent 3+⚡ this round', amount: 1 },
  },
  {
    id: 'credit_forecast',
    name: 'Credit Forecast',
    description: 'Rnd ≥8: extract +30%. Else: scan dng.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
  },
  {
    id: 'marathon',
    name: 'Marathon',
    description: '+1 rnd. 2-4 scrap.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
    energyRefund: { condition: 'Round number ≥5', amount: 1 },
  },
  {
    id: 'audit_immunity',
    name: 'Audit Immunity',
    description: 'Block next audit dng. 2-4 scrap.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
    energyRefund: { condition: 'Blocked audit-type danger', amount: 1 },
  },
  {
    id: 'mandate_override',
    name: 'Mandate Override',
    description: 'Debt −8000₡. Hull −5. 2-4 scrap.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
  },
  {
    id: 'debt_leveraging',
    name: 'Debt Leveraging',
    description: 'Debt −5000₡. 3-6 scrap.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'hostile_extraction',
    name: 'Hostile Extraction',
    description: 'End dive. 8-15 scrap. Debt +15000.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'debt_conversion',
    name: 'Debt Conversion',
    description: '10000₡ debt → 8000₡. 2-5 scrap.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
    energyRefund: { condition: 'Debt reduced by this card', amount: 1 },
  },
  {
    id: 'threat_analysis',
    name: 'Threat Analysis',
    description: 'Preview 3 dng. Dng −15% rest of run.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'sector_lockdown',
    name: 'Sector Lockdown',
    description: 'Skip dng. Debt +3000₡.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
    energyRefund: { condition: 'Spent 3+⚡ this round', amount: 1 },
  },
  {
    id: 'extended_contract',
    name: 'Extended Contract',
    description: '+2 rnds. 4-8 scrap.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
    energyRefund: { condition: 'Spent 3+⚡ this round', amount: 1 },
  },
  {
    id: 'efficiency_protocol',
    name: 'Efficiency Protocol',
    description: '5-10 scrap. Next rnd dng +20%.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
  },

  // ── Rare (11 cards) ────────────────────────────────────────────────────────
  {
    id: 'hull_investment',
    name: 'Hull Investment',
    description: '−20 hull. 4-8 scrap.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'corporate_lockdown',
    name: 'Corporate Lockdown',
    description: 'Skip 2 dng. Debt +15000₡.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'mass_extraction',
    name: 'Mass Extraction',
    description: 'End dive. 6-12 scrap. +40% extract. Hull −15.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'debt_write_off',
    name: 'Debt Write-Off',
    description: 'Debt −25000₡. Once/run.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'executive_order',
    name: 'Executive Order',
    description: '5-10 scrap. Skip 2 dng. Debt +12000₡.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'profit_margin',
    name: 'Profit Margin',
    description: '3-6 scrap. Extract +25%.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'sector_monopoly',
    name: 'Sector Monopoly',
    description: '6-10 scrap. Debt +20000₡.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'emergency_extraction',
    name: 'Emergency Extraction',
    description: 'End dive. 4-8 scrap. Hull <40: +3 scrap.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'hostile_takeover',
    name: 'Hostile Takeover',
    description: '10-18 scrap. Debt +30000₡. Hull −10.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'corporate_espionage',
    name: 'Corporate Espionage',
    description: '4-8 scrap. Extract +10%. +1 rare hw.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'full_audit',
    name: 'Full Audit',
    description: 'Run debt → ₡ at 50%.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
];
