import type { TacticCard } from './cards.ts';

export const SMUGGLER_CARDS: TacticCard[] = [
  // ── Common (7 cards) ─────────────────────────────────────────────────────
  {
    id: 'quick_loot',
    name: 'Quick Loot',
    description: '1-3 scrap. 20%: bonus component.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 0,
    overchargeEffect: { multiplier: 1.5, description: '+50% scrap (2-5)' },
  },
  {
    id: 'shadow_run',
    name: 'Shadow Run',
    description: '2-4 scrap. Next dng −10%.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 0,
    overchargeEffect: { multiplier: 1.5, description: '+50% scrap (3-6) and −15% next danger' },
  },
  {
    id: 'off_books',
    name: 'Off Books',
    description: '2-5 scrap. 30%: hull −10~15.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 0,
    overchargeEffect: { multiplier: 1.5, description: '+50% scrap (3-8)' },
  },
  {
    id: 'salvage_grab',
    name: 'Salvage Grab',
    description: '3-6 scrap.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 0,
    overchargeEffect: { multiplier: 1.5, description: '+50% scrap (5-9)' },
  },
  {
    id: 'risk_it',
    name: 'Risk It',
    description: '4-8 scrap. 35%: hull −12~22.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 1,
    overchargeEffect: { multiplier: 1.5, description: '+50% scrap (6-12)' },
  },
  {
    id: 'desperate_gamble',
    name: 'Desperate Gamble',
    description: 'Hull <30: gain 1⚡. 2-5 scrap.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 0,
    isSurge: true,
  },
  {
    id: 'emergency_reroute',
    name: 'Emergency Reroute',
    description: 'Hull <30: gain 1⚡, +3 scrap. Skip next dng.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 0,
    isSurge: true,
  },
  {
    id: 'opportunist',
    name: 'Opportunist',
    description: '1-3 scrap. Dng last rnd? +1 scrap.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 0,
  },
  {
    id: 'street_deal',
    name: 'Street Deal',
    description: '2-4 scrap. 25%: +1 comp.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 0,
  },

  // ── Uncommon (12 cards) ────────────────────────────────────────────────────
  {
    id: 'bot_swarm',
    name: 'Bot Swarm',
    description: 'Deploy 2 bots. +1000₡/bot.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'calculated_scrap',
    name: 'Calculated Scrap',
    description: 'Bots ≥3: 6-10 scrap hull −5. Else 2-4 scrap.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
  },
  {
    id: 'calculated_risk',
    name: 'Calculated Risk',
    description: 'Hull −15. 5-10 scrap. Dng −15% rest of run.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'adrenaline_junkie',
    name: 'Adrenaline Junkie',
    description: '4-10 scrap. Dng last rnd? +3-7 scrap more.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
  },
  {
    id: 'deep_salvage',
    name: 'Deep Salvage',
    description: '6-12 scrap. 1-3 comp. 40%: hull −15~25.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'sector_sweep',
    name: 'Sector Sweep',
    description: '3-7 scrap. 30%: +1 relic. 30%: hull −8~15.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
  },
  {
    id: 'ghost_claim',
    name: 'Ghost Claim',
    description: '5-12 scrap. Skip dng. Next rnd: −50% salvage.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
  },
  {
    id: 'salvage_protocol',
    name: 'Salvage Protocol',
    description: '2-5 scrap. +1 comp. Hull −5.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
  },
  {
    id: 'overclock_bots',
    name: 'Overclock Bots',
    description: 'All bots salvage +1 each.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'bot_army',
    name: 'Bot Army',
    description: 'Deploy 3 bots. Hull −10.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
  },
  {
    id: 'reinforced_bots',
    name: 'Reinforced Bots',
    description: 'Bots give hull +5 each on deploy.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'danger_rush',
    name: 'Danger Rush',
    description: '6-14 scrap. Dng +25% 2 rnds.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
  },

  // ── Rare (11 cards) ────────────────────────────────────────────────────────
  {
    id: 'danger_profit',
    name: 'Danger Profit',
    description: 'No dng this rnd: 4-8 scrap.',
    rarity: 'rare',
    lootNodeEligible: false,
    energyCost: 2,
  },
  {
    id: 'void_run',
    name: 'Void Run',
    description: '4-8 scrap. +2 echo. Hull −15.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'high_stakes',
    name: 'High Stakes',
    description: '10-20 scrap. 50%: lose shld. hull −20~35.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'black_ops',
    name: 'Black Ops',
    description: '2-4 scrap. +2 relics. Debt +15000₡.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'salvage_king',
    name: 'Salvage King',
    description: '8-18 scrap. 1-3 comp. 50%: relic. Hull −10.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'ghost_protocol',
    name: 'Ghost Protocol',
    description: '3-6 scrap. Skip 2 dng.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'maximum_risk',
    name: 'Maximum Risk',
    description: '12-25 scrap. Hull −25. −2 shld.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'bot_empire',
    name: 'Bot Empire',
    description: 'Deploy 5 bots. Extract: +20% if ≥5.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'underworld_contact',
    name: 'Underworld Contact',
    description: '6-12 scrap. +1 uncommon hw on extract.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'shadow_extraction',
    name: 'Shadow Extraction',
    description: 'End dive. 4-8 scrap. +30% extract. +2 echo.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'void_smuggler',
    name: 'Void Smuggler',
    description: '6-10 scrap. +3 echo. Debt +25000₡.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
];
