import type { TacticCard } from './cards.ts';

export const COOPERATIVE_CARDS: TacticCard[] = [
  // ── Common (7 cards) ───────────────────────────────────────────────────────
  {
    id: 'hull_patch',
    name: 'Hull Patch',
    description: 'Hull +12.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 0,
  },
  {
    id: 'group_effort',
    name: 'Group Effort',
    description: 'Hull +8. Shld +1.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 1,
  },
  {
    id: 'shared_repair',
    name: 'Shared Repair',
    description: 'Hull <50: +15 else +8.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 0,
  },
  {
    id: 'solidarity',
    name: 'Solidarity',
    description: 'Hull +6. Next crew card: 0₡.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 0,
  },
  {
    id: 'team_shield',
    name: 'Team Shield',
    description: '+2 shld.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 1,
    overchargeEffect: { multiplier: 1.5, description: '+3 shld (+50% shield value for +1⚡)' },
  },
  {
    id: 'collective_hull',
    name: 'Collective Hull',
    description: 'Hull +10. Crew full? +1 shld.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 1,
  },
  {
    id: 'mutual_aid',
    name: 'Mutual Aid',
    description: 'Hull +8. Remove 1 debuff.',
    rarity: 'common',
    lootNodeEligible: true,
    energyCost: 0,
  },

  // ── Uncommon (12 cards) ────────────────────────────────────────────────────
  {
    id: 'shield_bash',
    name: 'Shield Bash',
    description: '−1 shld. Hull +15. ≥5 shld: +3000₡.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
    energyRefund: { condition: 'Shields ≥5 at play', amount: 1 },
  },
  {
    id: 'mass_shields',
    name: 'Mass Shields',
    description: '+shld = ceil(missing hull/20).',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
    overchargeEffect: { multiplier: 1.5, description: '+shld = ceil(missing hull/13) (+50% shield generation for +1⚡)' },
  },
  {
    id: 'fortress_protocol',
    name: 'Fortress Protocol',
    description: 'Shld ≥5 at rnd end: +2000₡.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
    energyRefund: { condition: 'Shields ≥5 at round end', amount: 1 },
  },
  {
    id: 'preemptive_shield',
    name: 'Preemptive Shield',
    description: 'Rnd ≤3: +2 shld. Else +1.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'triage',
    name: 'Triage',
    description: 'Hull +20. −3000₡.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
    energyRefund: { condition: 'Hull <30 before playing', amount: 1 },
  },
  {
    id: 'field_medicine',
    name: 'Field Medicine',
    description: 'Hull <40: +30. Else +10.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'emergency_repair',
    name: 'Emergency Repair',
    description: 'Hull +25. Hull <30: skip dng.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
    energyRefund: { condition: 'Hull <30 when played', amount: 1 },
  },
  {
    id: 'structural_reinforce',
    name: 'Structural Reinforce',
    description: 'Max hull +10. Hull +10.',
    rarity: 'uncommon',
    lootNodeEligible: false,
    energyCost: 1,
  },
  {
    id: 'adaptive_defense',
    name: 'Adaptive Defense',
    description: 'Hull +8. Dng −10% for 2 rnds.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
  },
  {
    id: 'crew_solidarity',
    name: 'Crew Solidarity',
    description: 'Hull +6/crew.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
    energyRefund: { condition: 'Full crew (3+ members)', amount: 1 },
  },
  {
    id: 'shield_wall_prep',
    name: 'Shield Wall Prep',
    description: '+3 shld. No shld next rnd.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
  },
  {
    id: 'hull_buffer',
    name: 'Hull Buffer',
    description: 'Hull +15. Max hull +5.',
    rarity: 'uncommon',
    lootNodeEligible: true,
    energyCost: 1,
  },

  // ── Rare (10 cards) ────────────────────────────────────────────────────────
  {
    id: 'shield_wall',
    name: 'Shield Wall',
    description: '−3 shld. Skip all dng this rnd.',
    rarity: 'rare',
    lootNodeEligible: false,
    energyCost: 2,
  },
  {
    id: 'last_bastion',
    name: 'Last Bastion',
    description: 'Hull >80: +3 shld. Once/run.',
    rarity: 'rare',
    lootNodeEligible: false,
    energyCost: 2,
  },
  {
    id: 'collective_recovery',
    name: 'Collective Recovery',
    description: 'Hull +20. All crew →full.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
    energyRefund: { condition: 'All crew were not full before playing', amount: 1 },
  },
  {
    id: 'mass_healing',
    name: 'Mass Healing',
    description: 'Hull +25. Shld +2.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'perimeter',
    name: 'Perimeter',
    description: '+4 shld. 2 rnds: dng −20%.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'bulwark_surge',
    name: 'Bulwark Surge',
    description: 'Hull +30. Shld +3. Hull −10 next rnd.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'fortress_lockdown',
    name: 'Fortress Lockdown',
    description: 'Skip dng. Shld ≥5: skip next too.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'hull_fortress',
    name: 'Hull Fortress',
    description: 'Hull +40. Max hull +15.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'crew_miracle',
    name: 'Crew Miracle',
    description: 'Hull ≤20: hull→80 +2 shld. Once.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
  {
    id: 'iron_covenant',
    name: 'Iron Covenant',
    description: 'Hull +20. Shld +2. All crew +1 shld.',
    rarity: 'rare',
    lootNodeEligible: true,
    energyCost: 2,
  },
];
